---
title: "Design of Portfolio of Stocks to Track an Index"
author: "Konstantinos Benidis and Daniel P. Palomar"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
  bookdown::html_document2:
    base_format: prettydoc::html_pretty
    theme: tactile
    highlight: vignette
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_depth: 2
header-includes:
  \allowdisplaybreaks
indent: yes
csl: ieee.csl
bibliography: refs.bib
vignette: >
  %\VignetteIndexEntry{Design of portfolio of stocks to track an index}
  %\VignetteKeyword{sparse, portfolio, financial index, tracking}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, echo = FALSE}
library(knitr)
opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.retina = 2,
  out.width = "75%",
  dpi = 96
)
knit_hooks$set(pngquant = hook_pngquant)
#Help on bookdown: https://bookdown.org/yihui/bookdown/
#rmarkdown::render("vignettes/SpectralGraphTopology-vignette.Rmd", "all")
#rmarkdown::render("vignettes/SpectralGraphTopology-vignette.Rmd", "bookdown::html_document2")
#rmarkdown::render("vignettes/SpectralGraphTopology-vignette.Rmd", "bookdown::pdf_document2")
#tools::compactPDF("vignettes/SpectralGraphTopology-vignette.pdf", gs_quality = "ebook")
```

-----------


# Comparison with other packages

# Usage of the package

# Explanation of the algorithms

## `learnGraphTopology`: Learning the topology of graph

The goal of `learnGraphTopology()` is to estimate the Laplacian matrix generated
by the weight vector of graph, $\mathbf{w}$.

> **Algorithm 1**

  1. Choose initial values for $\mathbf{w}$, $\mathbf{U}$, $\boldsymbol{\Lambda}$,
     and $\beta$, and compute $\mathcal{L}\mathbf{w}^{(0)}$
  2. Define the number of components $K$ and tunning parameters, $\alpha$, $\alpha_1$, $\alpha_2$, $\rho$
  3. Set $j=0$, while not converged do
  4. Set $i=0$, while not converged do
  5. Update $\mathbf{w}$, $\mathbf{w}^{(i+1)} \gets f_{\mathbf{w}}(\mathbf{w}^{(i)}, \mathbf{U}^{(i)}, \boldsymbol{\Lambda}^{(i)}, \beta, n, \mathbf{K})$
  6. Update $\mathbf{U}$, $\mathbf{U}^{(i+1)} \gets f_{\mathbf{U}}(\mathbf{w}^{(i+1)}, n, K)$
  7. Update $\boldsymbol{\Lambda}$, $\boldsymbol{\Lambda}^{(i+1)} \gets f_{\boldsymbol{\Lambda}}(\alpha_1, \alpha_2, \beta, \mathbf{w}^{(i+1)}, \mathbf{U}^{(i+1)}, n, K)$
  8. $i \gets i+1$
  9. $\beta \gets \beta(\rho + 1)$
  10. Repeat steps $4-9$ until convergence
  11. Compute $\mathcal{L}\mathbf{w}^{(i)}$
  12. $j \gets j+1$
  13. Repeat steps $3-12$ until convergence
  14. Return $\mathcal{L}\mathbf{w}^{(i)}$

# References {-}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\noindent
