#' Updates the value of w, the weight vector of the graph Laplacian
#'
#' @param w weight vector of the graph
#' @param Lw Laplacian matrix generated by the weight vector of the graph
#' @param U matrix whose columns represent the eigen vectors of the Laplacian
#' matrix in increasing order
#' @param β scalar that controls the strength of the regularization term
#' @param λ vector whose entries are the eigenvalues of the Laplacian in
#' increasing order
#' @param N number of nodes
#' @param Kmat matrix (see section 1.1 for its definition)
#'
#' @return the updated value of w
laplacian.w_update <- function(w, Lw, U, beta, lambda, N, Kmat) {
  #grad_f <- Lstar(L(w) - U %*% diag(lambda) %*% t(U) + Kmat / beta)
  grad_f <- Lstar(Lw - crossprod(sqrt(lambda) * t(U)) + Kmat / beta)
  w_update <- w - .5 * grad_f / N
  w_update[w_update < 0] <- 0
  return(w_update)
}


#' Updates the value of U, the matrix whose columns represent the eigen vectors
#' of the Laplacian in increasing order
#'
#' @param Lw Laplacian matrix generated by the weight vector of the graph
#' @param N dimension of each data sample
#' @param K number of components of the graph
#'
#' @return the updated value of U
laplacian.U_update <- function(Lw, N, K) {
  return(eigenvectors(Lw)[, (K+1):N])
}


#' Updates the value of lambda, the vector whose entries correspond to the
#' eigenvalues of the Laplacian matrix
#'
#' @param lb lower bound on the eigenvalues of the Laplacian matrix
#' @param ub upper bound on the eigenvalues of the Laplacian matrix
#' @param β scalar that controls the strength of the regularization term
#' @param U matrix whose columns represent the eigen vectors of the Laplacian
#' matrix in increasing order
#' @param Lw Laplacian matrix generated by the weight vector of the graph
#' @param N dimension of each data sample
#' @param K number of components of the graph
#'
#' @return the updated value of λ
laplacian.lambda_update <- function(lb, ub, beta, U, Lw, N, K) {
  q <- N - K
  d <- diag(t(U) %*% Lw %*% U)
  lambda <- .5 * (d + sqrt(d^2 + 4 / beta)) # unconstrained solution as initial point
  eps <- 1e-9
  condition <- c((lambda[q] - ub) <= eps,
                 (lambda[1] - lb) >= -eps,
                 (lambda[2:q] - lambda[1:(q-1)]) >= -eps)
  if (all(condition)) {
    return (lambda)
  } else {
    greater_ub <- lambda > ub
    lesser_lb <- lambda < lb
    lambda[greater_ub] <- ub
    lambda[lesser_lb] <- lb
  }
  condition <- c((lambda[q] - ub) <= eps,
                 (lambda[1] - lb) >= -eps,
                 (lambda[2:q] - lambda[1:(q-1)]) >= -eps)
  if (all(condition)) {
    return (lambda)
  } else {
    stop("eigenvalues are not in increasing order")
  }
}


#' Updates the value of V, the matrix whose columns represent the eigenvectors
#' of the Adjacency in increasing order
#'
#' @param Lw Laplacian matrix generated by the weight vector of the graph
#' @param N number of nodes
#' @param K number of components of the graph
#'
#' @return the updated value of U
adjacency.V_update <- function(Aw, n, z) {
  V <- eigenvectors(Aw)
  return(cbind(V[, 1:(.5*(n - z))], V[, (1 + .5*(n + z)):n]))
}


#' Updates the value of w, the weight vector of the graph adjacency matrix
#'
#' @param w weight vector of the graph
#' @param Lw Laplacian matrix generated by the weight vector of the graph
#' @param U matrix whose columns represent the eigen vectors of the Laplacian
#' matrix in increasing order
#' @param β scalar that controls the strength of the regularization term
#' @param λ vector whose entries are the eigenvalues of the Laplacian in
#' increasing order
#' @param N number of nodes
#' @param Kmat matrix (see section 1.1 for its definition)
#'
#' @return the updated value of w
adjacency.w_update <- function(w, Aw, V, beta, psi, Kmat, J, Lips) {
  grad_h <- 2 * w - Astar(V %*% diag(psi) %*% t(V)) + Lstar(Kmat) / beta
  w_update <- w - (Lstar(inv_sympd(L(w) + J))/beta + grad_h) / (2 + Lips/beta)
  w_update[w_update < 0] <- 0
  return(w_update)
}


#' Updates the value of psi, the vector whose entries correspond to the
#' eigenvalues of the adjacency matrix
#'
#' @param V matrix whose columns represent the eigen vectors of the Laplacian
#' matrix in increasing order
#' @param Aw Adjacency matrix generated by the weight vector of the graph
adjacency.psi_update <- function(V, Aw) {
  return(isoreg(diag(t(V) %*% Aw %*% V))$yf)
}

adjacency.initial_psi <- function(V, Aw) {
  c <- diag(t(V) %*% Aw %*% V)
  q <- length(c)
  psi <- CVXR::Variable(q)
  objective <- CVXR::Minimize(sum((psi - c) ^ 2))
  constraints <- list(psi[1:(q - 1)] < psi[2:q])
  j <- length(constraints) + 1
  i <- 1
  while (i < q + 1 - i) {
    constraints[[j]] <- psi[i] == -psi[q + 1 - i]
    j <- j + 1
    i <- i + 1
  }
  prob <- CVXR::Problem(objective, constraints)
  result <- solve(prob)
  return(as.vector(result$getValue(psi)))
}

joint.w_update <- function(w, Lw, U, d, beta, lambda, N, Kmat) {
  n <- ncol(Lw)
  ULmdUT <- crossprod(sqrt(lambda) * t(U))
  grad_f <- 2 * w + Lstar(Lw + ULmdUT - Kmat/beta) + Astar(ULmdUT - diag(d, n))
}
