# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

_LOp <- function(w, n) {
    .Call('_spectralGraphTopology__LOp', PACKAGE = 'spectralGraphTopology', w, n)
}

_LStarOp <- function(Y) {
    .Call('_spectralGraphTopology__LStarOp', PACKAGE = 'spectralGraphTopology', Y)
}

