# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppLOp <- function(w, n) {
    .Call('_spectralGraphTopology_CppLOp', PACKAGE = 'spectralGraphTopology', w, n)
}

CppLStarOpImpl <- function(Y) {
    .Call('_spectralGraphTopology_CppLStarOpImpl', PACKAGE = 'spectralGraphTopology', Y)
}

CppLStarOp <- function(Y) {
    .Call('_spectralGraphTopology_CppLStarOp', PACKAGE = 'spectralGraphTopology', Y)
}

