# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the Laplacian linear operator which maps a vector of weights into
#' a valid Laplacian matrix.
#'
#' @param w weight vector of the graph
#' @return Lw the Laplacian matrix
#'
#' @export
L <- function(w) {
    .Call('_spectralGraphTopology_L', PACKAGE = 'spectralGraphTopology', w)
}

#' Computes the matrix that represents the composition of
#' the vec and the L operators.
#'
#' @param n the dimension of L
#' @return R matrix such that vec(L(w)) = Rw
#'
#' @export
vecLmat <- function(n) {
    .Call('_spectralGraphTopology_vecLmat', PACKAGE = 'spectralGraphTopology', n)
}

#' Computes the canonical vec operator, i.e., converts a given n x m matrix M,
#' into a  nm x 1 column vector vec(M) by stacking the columns of M on top of
#' one another.
#'
#' @param M input matrix
#' @return w vector such that w = vec(M)
#'
#' @export
vec <- function(M) {
    .Call('_spectralGraphTopology_vec', PACKAGE = 'spectralGraphTopology', M)
}

#' Computes the Lstar operator.
#'
#' @param M matrix
#' @return w vector
#'
#' @export
Lstar <- function(M) {
    .Call('_spectralGraphTopology_Lstar', PACKAGE = 'spectralGraphTopology', M)
}

#' Computes the inverse of the L operator.
#'
#' @param M Laplacian matrix
#' @return w the weight vector of the graph
#'
#' @export
Linv <- function(M) {
    .Call('_spectralGraphTopology_Linv', PACKAGE = 'spectralGraphTopology', M)
}

#' Alternative implementation for the Lstar operator.
#' This is only used for unit testing. Use Lstar for
#' a better performance.
#'
#' @param M matrix
#' @param w vector
#'
altLstar <- function(M) {
    .Call('_spectralGraphTopology_altLstar', PACKAGE = 'spectralGraphTopology', M)
}

blockDiagCpp <- function(matrices) {
    .Call('_spectralGraphTopology_blockDiagCpp', PACKAGE = 'spectralGraphTopology', matrices)
}

